import { PROPOSAL_STATUS, ROLES } from './constants';

export const MOCK_USERS = [
  { id: 'u1', name: 'Anushree Jain', email: 'anushree@university.edu', role: ROLES.STUDENT, avatar: '👩‍🎓' },
  { id: 'u2', name: 'Riya Sharma', email: 'riya@university.edu', role: ROLES.SOCIETY, clubId: 'c1', clubName: 'Tech Society', avatar: '👩‍💻' },
  { id: 'u3', name: 'Arjun Mehta', email: 'arjun@university.edu', role: ROLES.SOCIETY, clubId: 'c2', clubName: 'Cultural Club', avatar: '🎭' },
  { id: 'u4', name: 'Dr. Priya Kapoor', email: 'priya.k@university.edu', role: ROLES.FACULTY, assignedClubs: ['c1', 'c2'], avatar: '👩‍🏫' },
  { id: 'u5', name: 'Dr. Rajesh Nair', email: 'rajesh.n@university.edu', role: ROLES.FACULTY, assignedClubs: ['c3'], avatar: '👨‍🏫' },
  { id: 'u6', name: 'Vikram Singh', email: 'vikram@university.edu', role: ROLES.ADMIN, avatar: '🛡️' },
  { id: 'u7', name: 'Neha Gupta', email: 'neha@university.edu', role: ROLES.SOCIETY, clubId: 'c3', clubName: 'Sports Committee', avatar: '⚽' },
  { id: 'u8', name: 'Kabir Patel', email: 'kabir@university.edu', role: ROLES.STUDENT, avatar: '👨‍🎓' },
];

export const MOCK_CLUBS = [
  { id: 'c1', name: 'Tech Society', description: 'Technology and innovation events', facultyAdvisorId: 'u4', leaderId: 'u2', memberCount: 85 },
  { id: 'c2', name: 'Cultural Club', description: 'Art, music, dance and cultural events', facultyAdvisorId: 'u4', leaderId: 'u3', memberCount: 120 },
  { id: 'c3', name: 'Sports Committee', description: 'Sports tournaments and fitness events', facultyAdvisorId: 'u5', leaderId: 'u7', memberCount: 95 },
];

export const MOCK_VENUES = [
  {
    id: 'v1',
    name: 'Main Auditorium',
    type: 'auditorium',
    capacity: 500,
    description: 'State-of-the-art auditorium with projection, lighting, and sound system',
    amenities: ['Projector', 'Sound System', 'AC', 'Stage Lighting', 'Backstage Area'],
    image: '🎭',
    allowedEventTypes: ['fest', 'talk', 'cultural', 'competition'],
    blockedDates: ['2026-04-01', '2026-04-15'],
  },
  {
    id: 'v2',
    name: 'Seminar Hall A',
    type: 'seminar_hall',
    capacity: 150,
    description: 'Modern seminar hall with tiered seating and AV equipment',
    amenities: ['Projector', 'Whiteboard', 'AC', 'Mic System'],
    image: '🎓',
    allowedEventTypes: ['workshop', 'talk', 'hackathon', 'meetup'],
    blockedDates: [],
  },
  {
    id: 'v3',
    name: 'Open Air Theatre',
    type: 'open_ground',
    capacity: 1000,
    description: 'Large open ground with stage and seating arrangements',
    amenities: ['Stage', 'Open Seating', 'Power Outlets', 'Temporary Lighting'],
    image: '🌳',
    allowedEventTypes: ['fest', 'cultural', 'sports', 'competition'],
    blockedDates: ['2026-04-10'],
  },
  {
    id: 'v4',
    name: 'Classroom Block A-101',
    type: 'classroom',
    capacity: 60,
    description: 'Standard classroom with smart board and AC',
    amenities: ['Smart Board', 'AC', 'Desks'],
    image: '📚',
    allowedEventTypes: ['workshop', 'talk', 'meetup', 'hackathon'],
    blockedDates: [],
  },
  {
    id: 'v5',
    name: 'Conference Room',
    type: 'conference_room',
    capacity: 30,
    description: 'Executive conference room with video conferencing setup',
    amenities: ['Projector', 'Video Conferencing', 'AC', 'Whiteboard'],
    image: '💼',
    allowedEventTypes: ['meetup', 'talk', 'workshop'],
    blockedDates: [],
  },
  {
    id: 'v6',
    name: 'Computer Lab 1',
    type: 'lab',
    capacity: 40,
    description: 'High-performance computer lab with 40 workstations',
    amenities: ['40 PCs', 'Projector', 'AC', 'High-speed Internet'],
    image: '💻',
    allowedEventTypes: ['workshop', 'hackathon', 'competition'],
    blockedDates: [],
  },
];

const today = new Date();
const formatDate = (daysOffset) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
};

export const MOCK_PROPOSALS = [
  {
    id: 'p1',
    title: 'CodeFest 2026 — Annual Hackathon',
    eventType: 'hackathon',
    description: 'A 24-hour coding marathon where students build innovative solutions to real-world problems. Teams of 2-4 compete for prizes. Includes mentoring sessions, workshops, and networking with industry professionals.',
    expectedAttendees: 120,
    date: formatDate(10),
    timeSlot: 'morning_1',
    venueId: 'v2',
    clubId: 'c1',
    clubName: 'Tech Society',
    submittedBy: 'u2',
    submittedByName: 'Riya Sharma',
    resources: 'Projector, Wi-Fi access, Power strips, Snacks & drinks for participants, Prizes for top 3 teams',
    documents: [{ name: 'sponsor_letter.pdf', type: 'pdf' }, { name: 'event_poster.png', type: 'image' }],
    status: PROPOSAL_STATUS.FACULTY_REVIEW,
    currentReviewer: 'u4',
    createdAt: formatDate(-3),
    updatedAt: formatDate(-1),
    auditTrail: [
      { action: 'created', by: 'u2', byName: 'Riya Sharma', at: formatDate(-3), note: 'Proposal created' },
      { action: 'submitted', by: 'u2', byName: 'Riya Sharma', at: formatDate(-2), note: 'Submitted for review' },
      { action: 'forwarded', by: 'system', byName: 'System', at: formatDate(-2), note: 'Forwarded to Faculty Advisor Dr. Priya Kapoor' },
    ],
  },
  {
    id: 'p2',
    title: 'Rhythm & Blues — Cultural Night',
    eventType: 'cultural',
    description: 'An evening of music, dance and drama performances by various student groups. Features live band performance, solo and group dance competitions, and a stand-up comedy segment.',
    expectedAttendees: 400,
    date: formatDate(15),
    timeSlot: 'evening_2',
    venueId: 'v1',
    clubId: 'c2',
    clubName: 'Cultural Club',
    submittedBy: 'u3',
    submittedByName: 'Arjun Mehta',
    resources: 'Stage Lighting (extra), Sound system with 4 mics, Green room access, 200 chairs for audience',
    documents: [{ name: 'event_schedule.pdf', type: 'pdf' }],
    status: PROPOSAL_STATUS.ADMIN_REVIEW,
    currentReviewer: 'u6',
    createdAt: formatDate(-7),
    updatedAt: formatDate(-2),
    auditTrail: [
      { action: 'created', by: 'u3', byName: 'Arjun Mehta', at: formatDate(-7), note: 'Proposal created' },
      { action: 'submitted', by: 'u3', byName: 'Arjun Mehta', at: formatDate(-6), note: 'Submitted for review' },
      { action: 'approved', by: 'u4', byName: 'Dr. Priya Kapoor', at: formatDate(-4), note: 'Approved. Great lineup planned.' },
      { action: 'forwarded', by: 'u4', byName: 'Dr. Priya Kapoor', at: formatDate(-4), note: 'Forwarded to HoD' },
      { action: 'approved', by: 'system', byName: 'HoD (Auto)', at: formatDate(-3), note: 'HoD approved' },
      { action: 'forwarded', by: 'system', byName: 'System', at: formatDate(-3), note: 'Forwarded to Admin' },
    ],
  },
  {
    id: 'p3',
    title: 'Inter-College Cricket Tournament',
    eventType: 'sports',
    description: 'Annual inter-college cricket tournament featuring 8 college teams. Two-day event with league matches and knock-out rounds.',
    expectedAttendees: 300,
    date: formatDate(20),
    timeSlot: 'morning_1',
    venueId: 'v3',
    clubId: 'c3',
    clubName: 'Sports Committee',
    submittedBy: 'u7',
    submittedByName: 'Neha Gupta',
    resources: 'Cricket kits, Scoreboard, First-aid kit, Trophies, Tent & seating for audience',
    documents: [{ name: 'team_registrations.xlsx', type: 'doc' }, { name: 'rules.pdf', type: 'pdf' }],
    status: PROPOSAL_STATUS.APPROVED,
    currentReviewer: null,
    createdAt: formatDate(-14),
    updatedAt: formatDate(-5),
    auditTrail: [
      { action: 'created', by: 'u7', byName: 'Neha Gupta', at: formatDate(-14), note: 'Proposal created' },
      { action: 'submitted', by: 'u7', byName: 'Neha Gupta', at: formatDate(-13), note: 'Submitted for review' },
      { action: 'approved', by: 'u5', byName: 'Dr. Rajesh Nair', at: formatDate(-11), note: 'Approved. Ensure safety measures are in place.' },
      { action: 'approved', by: 'system', byName: 'HoD (Auto)', at: formatDate(-9), note: 'HoD approved' },
      { action: 'approved', by: 'u6', byName: 'Vikram Singh', at: formatDate(-7), note: 'Admin approved. Venue booked.' },
      { action: 'venue_booked', by: 'system', byName: 'System', at: formatDate(-7), note: 'Open Air Theatre booked for the event' },
    ],
  },
  {
    id: 'p4',
    title: 'AI & Machine Learning Workshop',
    eventType: 'workshop',
    description: 'Hands-on workshop covering fundamentals of machine learning, neural networks, and practical applications using Python and TensorFlow. Includes a mini-project session.',
    expectedAttendees: 35,
    date: formatDate(5),
    timeSlot: 'afternoon_2',
    venueId: 'v6',
    clubId: 'c1',
    clubName: 'Tech Society',
    submittedBy: 'u2',
    submittedByName: 'Riya Sharma',
    resources: 'Lab PCs with Python/TensorFlow pre-installed, Projector, Printed handouts',
    documents: [{ name: 'speaker_bio.pdf', type: 'pdf' }, { name: 'workshop_outline.pdf', type: 'pdf' }],
    status: PROPOSAL_STATUS.VENUE_BOOKED,
    currentReviewer: null,
    createdAt: formatDate(-20),
    updatedAt: formatDate(-10),
    auditTrail: [
      { action: 'created', by: 'u2', byName: 'Riya Sharma', at: formatDate(-20), note: 'Proposal created' },
      { action: 'submitted', by: 'u2', byName: 'Riya Sharma', at: formatDate(-19), note: 'Submitted for review' },
      { action: 'approved', by: 'u4', byName: 'Dr. Priya Kapoor', at: formatDate(-17), note: 'Excellent initiative. Approved.' },
      { action: 'approved', by: 'system', byName: 'HoD (Auto)', at: formatDate(-15), note: 'HoD approved' },
      { action: 'approved', by: 'u6', byName: 'Vikram Singh', at: formatDate(-12), note: 'Approved and venue confirmed.' },
      { action: 'venue_booked', by: 'system', byName: 'System', at: formatDate(-12), note: 'Computer Lab 1 booked.' },
    ],
  },
  {
    id: 'p5',
    title: 'Startup Pitch Night',
    eventType: 'talk',
    description: 'Students present their startup ideas to a panel of entrepreneurs and VCs. Top 3 ideas receive seed funding support.',
    expectedAttendees: 80,
    date: formatDate(25),
    timeSlot: 'evening_1',
    venueId: 'v2',
    clubId: 'c1',
    clubName: 'Tech Society',
    submittedBy: 'u2',
    submittedByName: 'Riya Sharma',
    resources: 'Projector, Stage mic, Timer display, Refreshments',
    documents: [],
    status: PROPOSAL_STATUS.DRAFT,
    currentReviewer: null,
    createdAt: formatDate(-1),
    updatedAt: formatDate(-1),
    auditTrail: [
      { action: 'created', by: 'u2', byName: 'Riya Sharma', at: formatDate(-1), note: 'Draft created' },
    ],
  },
  {
    id: 'p6',
    title: 'Annual Day Celebration',
    eventType: 'fest',
    description: 'Grand celebration of the university founding day with cultural performances, guest speeches, and award ceremony for outstanding students and faculty members.',
    expectedAttendees: 450,
    date: formatDate(8),
    timeSlot: 'afternoon_1',
    venueId: 'v1',
    clubId: 'c2',
    clubName: 'Cultural Club',
    submittedBy: 'u3',
    submittedByName: 'Arjun Mehta',
    resources: 'Full stage setup, Sound system, Flower decorations, Guest seating arrangement, Awards/trophies',
    documents: [{ name: 'guest_list.pdf', type: 'pdf' }, { name: 'event_schedule.pdf', type: 'pdf' }],
    status: PROPOSAL_STATUS.REVISION_REQUESTED,
    currentReviewer: 'u4',
    createdAt: formatDate(-10),
    updatedAt: formatDate(-4),
    auditTrail: [
      { action: 'created', by: 'u3', byName: 'Arjun Mehta', at: formatDate(-10), note: 'Proposal created' },
      { action: 'submitted', by: 'u3', byName: 'Arjun Mehta', at: formatDate(-9), note: 'Submitted for review' },
      { action: 'revision_requested', by: 'u4', byName: 'Dr. Priya Kapoor', at: formatDate(-4), note: 'Please add detailed budget breakdown and confirm guest speaker availability.' },
    ],
  },
];

export const MOCK_BOOKINGS = [
  { id: 'b1', venueId: 'v3', proposalId: 'p3', date: formatDate(20), timeSlot: 'morning_1', status: 'confirmed' },
  { id: 'b2', venueId: 'v6', proposalId: 'p4', date: formatDate(5), timeSlot: 'afternoon_2', status: 'confirmed' },
  { id: 'b3', venueId: 'v1', proposalId: null, date: formatDate(3), timeSlot: 'morning_2', status: 'maintenance', note: 'Scheduled maintenance' },
];

export const MOCK_NOTIFICATIONS = [
  { id: 'n1', userId: 'u2', type: 'revision', title: 'Revision Requested', message: 'Dr. Priya Kapoor has requested changes to "Annual Day Celebration"', proposalId: 'p6', read: false, createdAt: formatDate(-4) },
  { id: 'n2', userId: 'u2', type: 'booking', title: 'Venue Booked!', message: 'Computer Lab 1 has been booked for "AI & ML Workshop"', proposalId: 'p4', read: true, createdAt: formatDate(-12) },
  { id: 'n3', userId: 'u4', type: 'submission', title: 'New Proposal', message: 'Tech Society submitted "CodeFest 2026 — Annual Hackathon" for review', proposalId: 'p1', read: false, createdAt: formatDate(-2) },
  { id: 'n4', userId: 'u6', type: 'approval', title: 'Pending Approval', message: '"Rhythm & Blues — Cultural Night" is awaiting your final approval', proposalId: 'p2', read: false, createdAt: formatDate(-3) },
  { id: 'n5', userId: 'u3', type: 'revision', title: 'Revision Requested', message: 'Dr. Priya Kapoor has requested changes to "Annual Day Celebration"', proposalId: 'p6', read: false, createdAt: formatDate(-4) },
  { id: 'n6', userId: 'u7', type: 'approval', title: 'Proposal Approved!', message: '"Inter-College Cricket Tournament" has been fully approved and venue is booked', proposalId: 'p3', read: true, createdAt: formatDate(-7) },
];
